version: '2'
services:
  mailserver:
    image: marooou/postfix-roundcube:latest
    ports:
      - 25:25
      - 80:80
      - 110:110
      - 143:143
      - 465:465
      - 993:993
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/vmail:/var/vmail
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWD=1234
      - DOMAIN_NAME=jsp.local
      - USERS=luis:ASIR2023,mati:ASIR2023,javsanpae:ASIR2023
    dns: 192.168.56.101
    container_name: mail-server
