# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bullseye64"
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.linked_clone = true
  end

  # Común a todas las máquinas
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
  SHELL

  ####################################################################
  # dns.sistema.sol
  ####################################################################
  
  config.vm.define "dns" do |dns|

    dns.vm.provider "virtualbox" do |vb|
      vb.name = "http-lab-1-dns"
      vb.memory = "256"
    end

    dns.vm.hostname = "tierra.sistema.sol"    
    dns.vm.network :private_network, ip: "192.168.57.103", hostname: true

    dns.vm.provision "bind9", type: "shell", inline: <<-SHELL
      route add default gw 192.168.0.1 #añadir puerta de enlace
      apt-get install -y bind9 bind9-utils bind9-doc

      # c
      cp -v /vagrant/dns/named /etc/default/
      cp -v /vagrant/dns/named.conf.options /etc/bind
      cp -v /vagrant/dns/named.conf.local /etc/bind
      cp -v /vagrant/dns/sistema.sol.dns /var/lib/bind
      cp -v /vagrant/dns/192.168.57.dns /var/lib/bind

      systemctl restart bind9
      systemctl status bind9
    SHELL
    
  end

  ####################################################################
  # mercurio.sistema.sol
  ####################################################################

  config.vm.define "mercurio" do |mercurio|
    mercurio.vm.provider "virtualbox" do |vb|
      vb.name = "http-lab-1-web"
      vb.memory = "256"
    end

    mercurio.vm.hostname = "mercurio.sistema.sol"
    mercurio.vm.network :private_network, ip: "192.168.57.101", hostname: true
    
    mercurio.vm.provision "apache", type: "shell", inline: <<-SHELL
      route add default gw 192.168.0.1 #añadir puerta de enlace
      apt-get install -y apache2

      # Copiar ficheros de configuración de apache2 que incluyen
      # apache2.conf, apolo.sistema.sol.conf y soyuz.sistema.sol
      # a su lugar correcto
      cp -v /vagrant/web/apolo.sistema.sol.conf /etc/apache2/sites-available/
      a2ensite apolo.sistema.sol.conf
      cp -v /vagrant/web/soyuz.sistema.sol.conf /etc/apache2/sites-available/
      a2ensite soyuz.sistema.sol.conf

      # Enlazamos el directorio raíz de nuestras webs dentro de el
      # servidor con la carpeta que tenemos fuera de la MV

      if ! [ -L /var/www/apolo.sistema.sol ]; then
        rm -rf /var/www/apolo.sistema.sol 
        ln -fs /vagrant/web/apolo.sistema.sol /var/www/apolo.sistema.sol
      fi

      if ! [ -L /var/www/soyuz.sistema.sol ]; then
        rm -rf /var/www/soyuz.sistema.sol
        ln -fs /vagrant/web/soyuz.sistema.sol /var/www/soyuz.sistema.sol
      fi

      systemctl restart apache2

    SHELL
  end
end
